// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF0nF5XSE86Hz6HL8EC5Fd-mm6C7fQPAs',
    appId: '1:58535978019:android:eef004457886876039fd96',
    messagingSenderId: '58535978019',
    projectId: 'bank-app-3a607',
    databaseURL: 'https://bank-app-3a607-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-3a607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXpB02djU0Zjyeio5IMPrbC8R0UD-9nw',
    appId: '1:58535978019:ios:1f8b8f5589f8309739fd96',
    messagingSenderId: '58535978019',
    projectId: 'bank-app-3a607',
    databaseURL: 'https://bank-app-3a607-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-3a607.appspot.com',
    androidClientId: '58535978019-3bdefjs641kbm3r0a9vijlcn6v1gjrre.apps.googleusercontent.com',
    iosClientId: '58535978019-kj1dpsgqs47pdae2va7fjoice1c3e0tv.apps.googleusercontent.com',
    iosBundleId: 'uz.hilola.pay',
  );
}
